apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sneakertail/product-service.git
    targetRevision: dev
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
